server:
  port: 8085
spring:
  application:
    name: parking-space
  datasource:
    url: jdbc:mysql:/SMPSParkingCrudDb?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka