server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:/SMPSUserCrudDb?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka